repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: ./node_modules/.bin/prettier --write
        language: system
        types_or: [ts, tsx]
      - id: eslint
        name: eslint
        entry: ./node_modules/.bin/eslint --fix
        language: system
        types_or: [ts, tsx]
